#!/usr/bin/env python3
"""Copy the scoring rules into the file the leaderboard worker imports.

The worker recalculates every score it is sent rather than trusting the number the
browser reports - that is the whole reason the leaderboard is worth reading. But a
recalculation is only useful if it matches the game: if the worker and the game drift
apart, honest players get marked down for scores they really did earn.

So the constants are written once, in data/rules.json, and copied from there into a
file the worker imports. tests/test_packs.py regenerates this file and fails if it
differs from what is checked in, which turns drift into a red test rather than a slow
leak of wrong scores.

The size of every round is folded in too. Without it the worker has nothing to measure
"twenty found out of nineteen" against, and an impossible score walks onto the board.

    python scripts/generate_worker_rules.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RULES = REPO_ROOT / "data" / "rules.json"
ROUNDS = REPO_ROOT / "data" / "rounds"
OUTPUT = REPO_ROOT / "worker" / "src" / "rules.generated.json"


def rules() -> dict:
    source = json.loads(RULES.read_text(encoding="utf-8"))
    out = {key: value for key, value in source.items() if not key.startswith("_")}
    out["_comment"] = "Generated by scripts/generate_worker_rules.py - do not edit by hand."
    # The live settings travel too: the worker owns the clock, so it is the worker
    # that has to know how long five minutes is.
    out["rounds"] = {
        data["id"]: len(data["items"])
        for data in (
            json.loads(path.read_text(encoding="utf-8"))
            for path in sorted(ROUNDS.glob("*.json"))
        )
    }
    return out


def render() -> str:
    return json.dumps(rules(), indent=2, sort_keys=True) + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
