#!/usr/bin/env python3
"""Turn a day's twelve drawings into one numbered picture.

Why this exists
---------------
The first round was drawn straight into a 500-line SVG in absolute coordinates,
and everything that went wrong with it went wrong for the same reason: a
vignette's position, its number, and the crop box the game zooms to were three
separate facts that had to be kept in agreement by hand. They did not stay in
agreement. One stray path dragged a vignette's bounding box a third of the way
down the canvas and sorted it into the wrong row; the numbers and the drawings
came apart; the boxes had to be re-measured every time anything moved.

So here the grid is the single fact. A drawing is authored in its own little
300x300 world, the generator decides where that world sits, and the number and
the crop box are both derived from the same placement. They cannot disagree,
because nobody writes them down twice.

Input:  data/scenes/<id>.json - twelve drawings, in the order they are numbered.
Output: app/scenes/<id>.svg, and the `box` of every item in data/rounds/<id>.json.

    python3 scripts/make_scene.py 2026-09-29
    python3 scripts/make_scene.py --all
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCENE_SRC = ROOT / "data" / "scenes"
SCENE_OUT = ROOT / "app" / "scenes"
ROUND_DIR = ROOT / "data" / "rounds"

# Four across, three down. Twelve is the size a five-minute round wants: enough
# to fill a picture, few enough that every one can be drawn properly.
COLS = 4
CELL = 300
MARGIN = 20
BADGE_R = 19

# The crop the game zooms to is the cell plus a little air, so a drawing that
# runs right to the edge of its cell is not clipped in the row that asks about it.
BLEED = 8


class BadScene(Exception):
    """A scene that would not draw correctly, described in words."""


def cell_origin(index: int) -> tuple[int, int]:
    """Top-left of the index-th cell, counting left to right then down."""
    col = index % COLS
    row = index // COLS
    return MARGIN + col * CELL, MARGIN + row * CELL


def box_for(index: int) -> list[int]:
    """The viewBox the game crops to for this cell: the cell, plus bleed."""
    x, y = cell_origin(index)
    return [x - BLEED, y - BLEED, CELL + BLEED * 2, CELL + BLEED * 2]


def canvas() -> tuple[int, int]:
    rows = 3
    return MARGIN * 2 + COLS * CELL, MARGIN * 2 + rows * CELL


HEAD = """<!--
  The picture for {title}.

  Generated by scripts/make_scene.py from data/scenes/{ident}.json - do not edit
  this file by hand, because the crop boxes in the round were worked out from
  the same grid and editing one without the other pulls them apart.

  Each vignette is drawn in its own 300x300 world and moved into place here, so
  a drawing's number and the crop the game zooms to come from one placement
  rather than from two hand-kept lists.
-->
<svg viewBox="0 0 {w} {h}" xmlns="http://www.w3.org/2000/svg" class="scene"
     role="img" aria-label="{alt}">
  <defs>
    <style>
      .scene .ink   {{ stroke: #2e1338; stroke-width: 3; stroke-linecap: round; stroke-linejoin: round; fill: none; }}
      .scene .fill  {{ stroke: #2e1338; stroke-width: 3; stroke-linejoin: round; }}
      .scene .thin  {{ stroke: #2e1338; stroke-width: 2; stroke-linecap: round; fill: none; }}
      .scene text   {{ font-family: ui-sans-serif, system-ui, sans-serif; }}
      .scene .badge-bg {{ fill: #4a0d68; stroke: #ffffff; stroke-width: 3; }}
      .scene .badge-no {{ fill: #ffffff; font: 700 24px ui-monospace, monospace; text-anchor: middle; }}
    </style>
  </defs>

  <rect x="0" y="0" width="{w}" height="{h}" rx="10" fill="#ffffff"/>
"""


def tint(index: int) -> str:
    """A wash behind alternating cells, so the twelve read as twelve."""
    return "#f7f4fa" if (index + index // COLS) % 2 == 0 else "#efe7f5"


def build(ident: str) -> None:
    src = SCENE_SRC / f"{ident}.json"
    if not src.exists():
        raise BadScene(f"no drawings for {ident}: {src} is missing")
    spec = json.loads(src.read_text(encoding="utf-8"))
    drawings = spec["drawings"]

    expected = COLS * 3
    if len(drawings) != expected:
        raise BadScene(f"{ident}: {len(drawings)} drawings, but the grid holds {expected}")

    numbers = [d["n"] for d in drawings]
    if numbers != list(range(1, expected + 1)):
        raise BadScene(f"{ident}: drawings must be numbered 1..{expected} in reading order, got {numbers}")

    w, h = canvas()
    out = [HEAD.format(title=spec.get("title", ident), ident=ident, w=w, h=h,
                       alt=spec.get("alt", f"A cartoon collage for {ident}"))]

    for index, drawing in enumerate(drawings):
        x, y = cell_origin(index)
        out.append(f'  <rect x="{x}" y="{y}" width="{CELL}" height="{CELL}" fill="{tint(index)}"/>')

    out.append("")
    for index, drawing in enumerate(drawings):
        x, y = cell_origin(index)
        body = drawing["svg"].strip()
        if "badge" in body:
            raise BadScene(f"{ident}: drawing {drawing['n']} draws its own badge; the generator does that")
        out.append(f'  <!-- {drawing["n"]}  {drawing.get("of", "")} -->')
        out.append(f'  <g class="vig" id="vig-{drawing["n"]}" transform="translate({x} {y})">')
        for line in body.splitlines():
            out.append("    " + line.strip())
        out.append("  </g>")
        out.append("")

    # Badges last so nothing is drawn over them.
    out.append("  <!-- the numbers, over everything -->")
    for index, drawing in enumerate(drawings):
        x, y = cell_origin(index)
        cx, cy = x + BADGE_R + 8, y + BADGE_R + 8
        out.append(f'  <circle cx="{cx}" cy="{cy}" r="{BADGE_R}" class="badge-bg"/>')
        out.append(f'  <text x="{cx}" y="{cy + 8}" class="badge-no">{drawing["n"]}</text>')

    out.append("</svg>")
    SCENE_OUT.mkdir(parents=True, exist_ok=True)
    (SCENE_OUT / f"{ident}.svg").write_text("\n".join(out) + "\n", encoding="utf-8")

    # And write the crops back into the round, so the two can never drift.
    round_path = ROUND_DIR / f"{ident}.json"
    if round_path.exists():
        data = json.loads(round_path.read_text(encoding="utf-8"))
        by_number = {item["n"]: item for item in data["items"]}
        for index, drawing in enumerate(drawings):
            item = by_number.get(drawing["n"])
            if item is None:
                raise BadScene(f"{ident}: drawing {drawing['n']} has no item in the round")
            item["box"] = box_for(index)
        round_path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                              encoding="utf-8")
    print(f"{ident}: {len(drawings)} drawings, {w}x{h}")


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 2
    idents = ([p.stem for p in sorted(SCENE_SRC.glob("*.json"))]
              if argv[0] == "--all" else argv)
    for ident in idents:
        build(ident)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except BadScene as err:
        print(f"error: {err}", file=sys.stderr)
        sys.exit(1)
